export const celebrities: string[] = [
    "Johnny Depp",
    "Arnold Schwarzenegger",
    "Jim Carrey",
    "Emma Watson",
    "Leonardo DiCaprio",
    "Tom Cruise",
    "Daniel Radcliffe",
    "Brad Pitt",
    "Charles Chaplin",
    "Morgan Freeman",
    "Tom Hanks",
    "Hugh Jackman",
    "Matt Damon",
    "Sylvester Stallone",
    "Will Smith",
    "Cameron Diaz",
    "George Clooney",
    "Harrison Ford",
    "Robert Downey Jr.",
    "Liam Neeson",
    "Mark Wahlberg",
    "Kate Winslet",
    "Natalie Portman",
    "Pierce Brosnan",
    "Justin Bieber",
    "Drake",
    "Kanye West",
    "Jennie Kim",
    "Lalisa Manoban",
    "Rosé",
    "Jisoo",
    "Orlando Bloom",
    "Dwayne Johnson",
    "Kevin Hart",
    "Angelina Jolie",
    "Adam Sandler",
    "Scarlett Johansson",
    "Jessica Alba",
    "Edward Norton",
    "Keira Knightley",
    "Gal Gadot",
    "Bradley Cooper",
    "Will Ferrell",
];
